### ISSUE TITLE
unfortunate error with Node vs 6.1.0

### ISSUE THREAD

**Issue by ORESoftware** [stephenwvickers/node-raw-socket#17] opened 2016-05-14 05:15 UTC
Opening a new issue to get your attention

We see this:

```

> raw-socket@1.4.0 install /Users/Olegzandr/WebstormProjects/suman/node_modules/raw-socket
> node-gyp rebuild

  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../src/raw.cc:6:
In file included from ../src/raw.h:23:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/raw/src/raw.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Olegzandr/WebstormProjects/suman/node_modules/raw-socket
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN babel-loader@6.2.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raw-socket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Olegzandr/WebstormProjects/suman/npm-debug.log

```

I would attach the npm-debug.log file, but we can't attach .log files to Github issues, apparently.

**Comment by stephenwvickers** [comment] 2016-05-15 19:51
You already had my attention.  I have to juggle this with other things, so I cannot always jump on to things as soon as people report them.

Closing this as it is a duplicate of #15.

**Closed by stephenwvickers** 2016-05-15 19:51 UTC

**Comment by ORESoftware** [comment] 2016-05-16 02:41
I don't read minds if I did I would be a psychic

**Comment by stephenwvickers** [comment] 2016-05-18 11:02
As I said I have to juggle this project with many other things in my life, such as my family, my job and my many other open source projects.

I took the time to open source this module to give back something to a community from which I have taken so much.

In return I expect a certain level of understanding and appreciation of the fact that this is all voluntary, in my free time, and I cannot always jump on to things immediately.

Please remember that the next time you choose to make comments like your last.

**Comment by ORESoftware** [comment] 2016-05-18 18:42
understood - your work is appreciated - so much appreciated than many projects depend on it. as the problem was breaking builds, I thought of it as priority.  In the future if you wish to avoid random people like me pinging you unnecessarily, it may behoove you to add a comment on the original issue (for which I opened a duplicate) and say "working on it" - even if you won't get to it for a couple days or weeks. The reason I opened this issue was because I saw no activity on the other one. Thank you for your work.
